### ISSUE TITLE
Ability to return a TypeMismatch error with custom logic

### ISSUE THREAD

**Issue by Hawk777** [pyfisch/minicbor#1]
I am implementing a CBOR decoder. At one point, my decoder needs to decode a value that could be a byte string or could be a UTF-8 string. The obvious way to do this seemed something like this (omitting indefinite length encodings for simplicity and because I don’t personally need them):

```
match d.datatype()? {
	Type::Bytes => {
		// Do the thing for a byte string.
	}
	Type::String => {
		// Do the thing for a UTF-8 string.
	}
	_ => Err(Error::TypeMismatch(something, "expected byte or UTF-8 string"))
}
```

But the missing piece of the puzzle is what the write for `something`. I can’t use `d.datatype()` because it doesn’t convert to a `u8`, and even if it did, it’s lossy. I can’t see any other function that would give me what I want either.

Assuming something like what I wrote is even reasonable, adding something like `datatype_raw` which returns a `u8` would be a small quality of life improvement.

**Comment by pyfisch** [comment]
This crate isn't finished and generally not yet intended to be used.

I don't understand how your question relates to this crate, as it doesn't have a `Type` enum. For casting enums to integers have a look at https://doc.rust-lang.org/rust-by-example/custom_types/enum/c_like.html

You might be looking for https://github.com/pyfisch/cbor

**Comment by Hawk777** [comment]
Sorry for bothering you; I was actually looking for [the other `minicbor`](https://crates.io/crates/minicbor).
